version: "2.3"

services:
  dask:
    restart: always
    container_name: dask
    build:
      context: build
    command: python3 run.py ${worker_size}
    ports:
      - "8786:8786"
      - "8787:8787"

  delete:
    links:
      - dask
    restart: always
    build:
      context: build
    command: python3 delete.py ${name} ${project} ${zone} ${expired}
